# Generated by Django 4.0.4 on 2022-05-09 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_cinema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'سینما', 'verbose_name_plural': 'سینما'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'فیلم', 'verbose_name_plural': 'فیلم'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=50, verbose_name='کارگردان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.IntegerField(verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(verbose_name='سال'),
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('salable_seats', models.IntegerField()),
                ('free_seats', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'فروش آغاز نشده'), (2, 'در حال فروش بلیت'), (3, 'بلیت ها تمام شد.'), (4, 'فروش بلیت بسته شد.'), (5, 'فیلم پخش شد.'), (6, 'سانس لغو شد.')])),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketing.movie')),
            ],
        ),
    ]
